name: Frontend Deployment
on:
    push:
      branches: [master,main]
jobs:

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v4

        - name: main
          if: ${{ github.event.ref == 'main' }}
          shell: bash
          run: |
            echo ${{ github.ref }}
          

        - name: master
          if: ${{ github.event.ref == 'master' }}
          shell: bash
          run: |
            echo ${{ github.ref }}
