name: Frontend Deployment
on:
    push:
      branches: [main,master]
jobs:

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v4

        - name: main
          if: ${{ github.ref == 'refs/heads/main' }}
          shell: bash
          run: |
            echo ${{ github.ref }}
          

        - name: master
          if: ${{ github.ref == 'refs/heads/master' }}
          shell: bash
          run: |
            echo ${{ github.ref }}
